trigger:
- main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Adjust based on your project's node version
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies"
    npm install
  displayName: 'Install Dependencies'

- script: |
    # Upload APK to BrowserStack and capture the app_url
    echo "Uploading APK to BrowserStack"
    APP_URL=$(curl -u "leona_xFi2Bk:NdxZZSj7DrrYnQVNfAoA" \
      -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \
      -F "file=@./app/app.apk" | jq -r '.app_url')
    echo "App uploaded. App URL: $APP_URL"
  displayName: 'Upload APK to BrowserStack'

- script: |
    # Upload Test Suite to BrowserStack and capture the test_suite_url
    echo "Uploading Test Suite to BrowserStack"
    TEST_SUITE_URL=$(curl -u "leona_xFi2Bk:NdxZZSj7DrrYnQVNfAoA" \
      -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" \
      -F "file=@./app/app-debug-androidTest.apk" | jq -r '.test_suite_url')
    echo "Test suite uploaded. Test Suite URL: $TEST_SUITE_URL"
  displayName: 'Upload Test Suite to BrowserStack'

- script: |
    # Trigger the Espresso Test Run on BrowserStack using app_url and test_suite_url
    echo "Triggering Espresso Test Run"
    curl -u "leona_xFi2Bk:NdxZZSj7DrrYnQVNfAoA" \
      -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
      -d '{
        "app": "'$APP_URL'",
        "testSuite": "'$TEST_SUITE_URL'",
        "devices": ["Samsung S23-9.0"]
      }' \
      -H "Content-Type: application/json"
  displayName: 'Trigger Test Run on BrowserStack'

