trigger:
- master  # Adjust the branch name as needed

pool:
  name: 'Azure Pipelines'  # Use this pool explicitly if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Adjust based on your project's Node.js version
  displayName: 'Install Node.js'

- script: |
    echo "Building APKs"
    # Run Gradle commands to build the main APK and test APK
    ./gradlew assemble  # This will build the main APK
    ./gradlew assembleAndroidTest  # This will build the test APK
  displayName: 'Build Main APK and Test APK'

- script: |
    echo "Running BrowserStack setup"
    # Install jq for JSON parsing
    sudo apt-get update && sudo apt-get install -y jq

    # Use the Azure DevOps variables in your script
    export BS_ACCESS_KEY=$(BROWSERSTACK_ACCESS_KEY)
    export BS_USERNAME=$(BROWSERSTACK_USERNAME)

    # Upload app to BrowserStack
    APP_RESPONSE=$(curl -u "$BS_USERNAME:$BS_ACCESS_KEY" \
      -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \
      -F "file=@$(Build.SourcesDirectory)/app/build/outputs/apk/debug/app-debug.apk" \
    APP_URL=$(echo $APP_RESPONSE | jq -r '.app_url')
    echo "App uploaded. App URL: $APP_URL"

    # Upload test suite to BrowserStack
    TEST_RESPONSE=$(curl -u "$BS_USERNAME:$BS_ACCESS_KEY" \
      -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" \
      -F "file=@$(Build.SourcesDirectory)/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" \
    TEST_URL=$(echo $TEST_RESPONSE | jq -r '.test_suite_url')
    echo "Test suite uploaded. Test URL: $TEST_URL"

    # Trigger the Espresso tests on BrowserStack
    BUILD_RESPONSE=$(curl -u "$BS_USERNAME:$BS_ACCESS_KEY" \
      -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
      -d '{"app": "'"$APP_URL"'", "testSuite": "'"$TEST_URL"'", "devices": ["Samsung Galaxy S23-13.0"]}' \
      -H "Content-Type: application/json")
    BUILD_ID=$(echo $BUILD_RESPONSE | jq -r '.build_id')
    echo "Build triggered. Build ID: $BUILD_ID"
  displayName: 'Upload App and Run Tests on BrowserStack'
